language: node_js
node_js:
- 16.13.0
cache: npm


install: 
  - npm ci
  - npm install
  - npm install --save-dev jest
before script:
  - npm start
script: 
  - npm test

# deploy:
#   provide: pages
#   skip-cleanup: true
#   github-token: $GITHUB_TOKEN
#   on:
#     branch: master
